USE master
GO

DROP DATABASE IF EXISTS PRS
GO

CREATE DATABASE PRS
GO

USE PRS
GO

CREATE TABLE Users
(
ID					INT					NOT NULL IDENTITY PRIMARY KEY,
Username			NVARCHAR(30)			NOT NULL UNIQUE,
Password			NVARCHAR(30)			NOT NULL,
FirstName			NVARCHAR(30)			NOT NULL,
LastName			NVARCHAR(30)			NOT NULL,
Phone				VARCHAR(12)			NULL,
Email				VARCHAR(255)		NULL,
IsReviewer			BIT					NOT NULL,
IsAdmin				BIT					NOT NULL
);





CREATE TABLE Vendors
(
ID			INT				NOT NULL IDENTITY PRIMARY KEY,
Code		VARCHAR(30)		NOT NULL UNIQUE,
Name		VARCHAR(30)		NOT NULL,
Address		VARCHAR(30)		NOT NULL,
City		VARCHAR(30)		NOT NULL,
State		VARCHAR(2)		NOT NULL,
Zip			VARCHAR(5)		NOT NULL,
Phone		VARCHAR(12)		NULL,
Email		VARCHAR(255)	NULL
);



CREATE TABLE Products
(
ID			INT				NOT NULL IDENTITY PRIMARY KEY,
PartNbr		VARCHAR(30)		NOT NULL UNIQUE,
Name		VARCHAR(30)		NOT NULL,
Price		DECIMAL(11,2)	NOT NULL,
Unit		VARCHAR(30)		NOT NULL,
PhotoPath	VARCHAR(255)	NULL,
VendorID	INT				NOT NULL REFERENCES Vendors(ID)
);


CREATE TABLE Requests
(
ID					INT					NOT NULL IDENTITY PRIMARY KEY,	
Description			VARCHAR(80)			NOT NULL,
Justification		VARCHAR(80)			NOT NULL,
RejectionReason		VARCHAR(80)			NULL,
DeliveryMode		VARCHAR(20)			NOT NULL DEFAULT 'Pickup',
SubmittedDate		DATE				NOT NULL DEFAULT GETDATE(),
DateNeeded			DATE				NOT NULL,
Status				VARCHAR(10)			NOT NULL DEFAULT 'NEW',
Total				DECIMAL(11,2)		NOT NULL DEFAULT 0,
UserID				INT					NOT NULL REFERENCES Users(ID)
);



CREATE TABLE RequestLine
(
ID				INT		NOT NULL IDENTITY PRIMARY KEY,
RequestID		INT		NOT NULL,
ProductID		INT		NOT NULL,
Quantity		INT		NOT NULL DEFAULT 1
);
